version: 0.2

env: 
  variables:
    S3_BUCKET: "pm-f" 
    APP_NAME: "pm-f"
phases: 
  install:
    runtime-versions: 
      nodejs: 10
    commands:
      - yarn install
      - npm install
  build: 
    commands:
      - echo Build started on `date` 
      - npm run build
  post_build: 
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket is cleared.
      - pwd
      - ls *
      - aws s3 cp build s3://${S3_BUCKET} --recursive 
      - echo Build completed on `date`
artifacts: 
  files:
    - build/**/*
  secondary-artifacts:
    pmf:
      files:
        - build/**/*